# Generated by Django 4.0.4 on 2022-05-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='owner',
            new_name='own',
        ),
    ]
