# Generated by Django 4.0.4 on 2022-05-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('time', models.TimeField()),
                ('category', models.URLField()),
            ],
        ),
    ]
