# Generated by Django 4.0.4 on 2022-05-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_alter_auctions_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='status',
            field=models.CharField(default='open', max_length=64),
        ),
    ]
